# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import session_service_pb2 as session__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in session_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """SessionService manages image-processing sessions and attached image blobs.
    REST equivalents live under /api/v1/sessions. Both transports call the same
    Python SessionService (ARCH-001).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/CreateSession',
                request_serializer=session__service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=session__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/GetSession',
                request_serializer=session__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=session__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/UpdateSession',
                request_serializer=session__service__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=session__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/DeleteSession',
                request_serializer=session__service__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=session__service__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/ListSessions',
                request_serializer=session__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=session__service__pb2.SessionListResponse.FromString,
                _registered_method=True)
        self.UploadImage = channel.stream_unary(
                '/pixeldive.session.v1.SessionService/UploadImage',
                request_serializer=session__service__pb2.ImageChunk.SerializeToString,
                response_deserializer=session__service__pb2.ImageUploadResponse.FromString,
                _registered_method=True)
        self.UploadImagesBatch = channel.stream_unary(
                '/pixeldive.session.v1.SessionService/UploadImagesBatch',
                request_serializer=session__service__pb2.BatchImageChunk.SerializeToString,
                response_deserializer=session__service__pb2.BatchUploadResponse.FromString,
                _registered_method=True)
        self.ListSessionImages = channel.unary_unary(
                '/pixeldive.session.v1.SessionService/ListSessionImages',
                request_serializer=session__service__pb2.ListImagesRequest.SerializeToString,
                response_deserializer=session__service__pb2.ImageListResponse.FromString,
                _registered_method=True)
        self.DownloadImage = channel.unary_stream(
                '/pixeldive.session.v1.SessionService/DownloadImage',
                request_serializer=session__service__pb2.DownloadImageRequest.SerializeToString,
                response_deserializer=session__service__pb2.ImageChunk.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """SessionService manages image-processing sessions and attached image blobs.
    REST equivalents live under /api/v1/sessions. Both transports call the same
    Python SessionService (ARCH-001).
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImagesBatch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessionImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=session__service__pb2.CreateSessionRequest.FromString,
                    response_serializer=session__service__pb2.SessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=session__service__pb2.GetSessionRequest.FromString,
                    response_serializer=session__service__pb2.SessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=session__service__pb2.UpdateSessionRequest.FromString,
                    response_serializer=session__service__pb2.SessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=session__service__pb2.DeleteSessionRequest.FromString,
                    response_serializer=session__service__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=session__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=session__service__pb2.SessionListResponse.SerializeToString,
            ),
            'UploadImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=session__service__pb2.ImageChunk.FromString,
                    response_serializer=session__service__pb2.ImageUploadResponse.SerializeToString,
            ),
            'UploadImagesBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadImagesBatch,
                    request_deserializer=session__service__pb2.BatchImageChunk.FromString,
                    response_serializer=session__service__pb2.BatchUploadResponse.SerializeToString,
            ),
            'ListSessionImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionImages,
                    request_deserializer=session__service__pb2.ListImagesRequest.FromString,
                    response_serializer=session__service__pb2.ImageListResponse.SerializeToString,
            ),
            'DownloadImage': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadImage,
                    request_deserializer=session__service__pb2.DownloadImageRequest.FromString,
                    response_serializer=session__service__pb2.ImageChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pixeldive.session.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pixeldive.session.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """SessionService manages image-processing sessions and attached image blobs.
    REST equivalents live under /api/v1/sessions. Both transports call the same
    Python SessionService (ARCH-001).
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/CreateSession',
            session__service__pb2.CreateSessionRequest.SerializeToString,
            session__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/GetSession',
            session__service__pb2.GetSessionRequest.SerializeToString,
            session__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/UpdateSession',
            session__service__pb2.UpdateSessionRequest.SerializeToString,
            session__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/DeleteSession',
            session__service__pb2.DeleteSessionRequest.SerializeToString,
            session__service__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/ListSessions',
            session__service__pb2.ListSessionsRequest.SerializeToString,
            session__service__pb2.SessionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pixeldive.session.v1.SessionService/UploadImage',
            session__service__pb2.ImageChunk.SerializeToString,
            session__service__pb2.ImageUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadImagesBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pixeldive.session.v1.SessionService/UploadImagesBatch',
            session__service__pb2.BatchImageChunk.SerializeToString,
            session__service__pb2.BatchUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessionImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixeldive.session.v1.SessionService/ListSessionImages',
            session__service__pb2.ListImagesRequest.SerializeToString,
            session__service__pb2.ImageListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pixeldive.session.v1.SessionService/DownloadImage',
            session__service__pb2.DownloadImageRequest.SerializeToString,
            session__service__pb2.ImageChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
